spring.application.name=restaurant
spring.sql.init.schema-locations=classpath:schema-restaurant.sql

# Habilita a execução do script de inicialização do banco
spring.sql.init.mode=always
# Desativa a criação automática do Hibernate para ele não conflitar com seu script SQL
spring.jpa.hibernate.ddl-auto=none

# Swagger / OpenAPI (springdoc)
# UI: http://localhost:8080/swagger-ui/index.html
# JSON: http://localhost:8080/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html