CREATE TABLE IF NOT EXISTS "address" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zip_code" varchar(9) NOT NULL,
  "street" varchar NOT NULL,
  "number" varchar NOT NULL,
  "city" varchar NOT NULL,
  "state" varchar(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_account" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "login" varchar NOT NULL,
  "password" varchar NOT NULL,
  "updated_at" timestamp NOT NULL,
  "address_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "customer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "cpf" varchar(14)
);

CREATE TABLE IF NOT EXISTS "restaurant" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "cnpj" varchar(18),
  "cuisine_type" varchar
);

-- Tabela pivô simplificada sem o created_at
CREATE TABLE IF NOT EXISTS "customer_restaurant" (
  "customer_id" integer NOT NULL,
  "restaurant_id" integer NOT NULL,
  PRIMARY KEY ("customer_id", "restaurant_id")
);

-- 1. Usuário aponta para Endereço
ALTER TABLE "user_account" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- 2. Cliente aponta para Usuário
ALTER TABLE "customer" ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- 3. Restaurante aponta para Usuário
ALTER TABLE "restaurant" ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- 4. Tabela pivô do relacionamento N:N
ALTER TABLE "customer_restaurant" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customer_restaurant" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("id") DEFERRABLE INITIALLY IMMEDIATE;